[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_swapper = "HezVxzdFxE8hfLJGp24nLQ31M6jjzJD8Uyj1QCxJGJ45"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./b6EH877xKSrB3Wo7xdUDTERyjaoexBQWUgo6TFyHYiw.json"

[scripts]
client = "npx tsx ./client"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
